// Fictional records for product exploration. No listing is a real job opening.
export const opportunities = [
  { id: "research-data", title: "Student Research Assistant", organization: "Center for Urban Futures", type: "Research", location: "Brooklyn campus", schedule: "8–10 hrs/week", compensation: "$25/hr", tags: ["Data analysis", "Research", "Python"], description: "Support a faculty team studying how urban communities access public services. Organize research data and summarize early findings.", eligibility: "Graduate students; experience with spreadsheets or Python is helpful.", daysUntilDeadline: 12, accent: "lilac" },
  { id: "dept-assistant", title: "Department Operations Assistant", organization: "School of Engineering", type: "On-campus job", location: "Brooklyn campus", schedule: "10–15 hrs/week", compensation: "$22/hr", tags: ["Operations", "Excel", "Communication"], description: "Help the department coordinate events, answer student questions, and maintain simple reporting spreadsheets.", eligibility: "Current students with strong organization and communication skills.", daysUntilDeadline: 9, accent: "peach" },
  { id: "teaching-analytics", title: "Analytics Course Assistant", organization: "Department of Technology Management", type: "Teaching", location: "Hybrid", schedule: "5–8 hrs/week", compensation: "$27/hr", tags: ["Analytics", "Teaching", "SQL"], description: "Support weekly workshops, answer questions, and provide feedback on introductory analytics assignments.", eligibility: "Graduate students who have completed an analytics course; SQL familiarity preferred.", daysUntilDeadline: 18, accent: "mint" },
  { id: "innovation-fellow", title: "Innovation Fellowship", organization: "Campus Innovation Lab", type: "Fellowship", location: "New York, NY", schedule: "Part-time", compensation: "Stipend", tags: ["Product", "Strategy", "Research"], description: "Work with a small interdisciplinary team to identify student problems, test ideas, and present a pilot plan.", eligibility: "Current graduate students from any discipline may apply.", daysUntilDeadline: 25, accent: "butter" },
  { id: "library-experience", title: "Library Experience Assistant", organization: "University Libraries", type: "On-campus job", location: "Manhattan campus", schedule: "6–12 hrs/week", compensation: "$21/hr", tags: ["Service", "UX research", "Operations"], description: "Assist visitors and help document recurring questions to improve the library experience.", eligibility: "Current students; customer-facing experience is a plus.", daysUntilDeadline: 16, accent: "mint" },
  { id: "climate-research", title: "Climate Data Researcher", organization: "Sustainability Institute", type: "Research", location: "Remote + campus", schedule: "8 hrs/week", compensation: "$26/hr", tags: ["Data visualization", "Research", "Excel"], description: "Clean and visualize campus sustainability data for a research team preparing a public report.", eligibility: "Current graduate students comfortable with spreadsheets and data storytelling.", daysUntilDeadline: 21, accent: "lilac" },
];

export const statuses = ["Saved", "Preparing", "Applied", "Interview", "Offer"];
